xywg:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

spring:
  redis:
    host: 192.168.1.143
    port: 6379
    password:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
      imagePath: /labor/
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: xywg-admin/src
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
      url: jdbc:mysql://192.168.1.143:3306/gblabor?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
      username: root
      password: Xingyun*_001
      db-name: gblabor
      filters: log4j,mergeStat

rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)
  swagger-open: true
jwt:
  header: Authorization   #http请求头所需要的字段
  secret: xy#wg#001        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: loginPost         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  standard-login: standardLogin  #通用版登陆
server:
  port: 8083 #项目端口
  name: labor-standard


#mybatis-plus:
#  mapper-locations: classpath*:com/xywg/admin/rest/**/mapping/*.xml
#  typeAliasesPackage: com.xywg.admin.rest.common.persistence.model
#  global-config:
#    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: true #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
#    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/xywg/admin/**/mapping/*.xml
  typeAliasesPackage: com.xywg.admin.modular.system.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用



logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: xywg-rest.log
  
ftp:
  host: 192.168.1.124
  port: 21
  username: lxjs
  password: 123.abc
  
#ftp:
#  host: 192.168.1.209
#  port: 21
#  username: labor
#  password: 123456