##########################################################
###################  正式环境的profile  ###################
##########################################################

xywg:
  ##########################################################
  ###################  任务调度配置        ###################
  ##########################################################
  job:
    admin:
      #addresses: http://192.168.10.158:8083
      addresses: http://192.168.1.159:8083
      #addresses: http://192.168.1.17:8083
    executor:
      appname: job-executor-labor
      ip:
      port: 9999
      logpath: logs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken: xywg666


spring:
  datasource:
      url: jdbc:mysql://192.168.1.143:3306/gblabor?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
      username: root
      password: Xingyun*_001
      db-name: gblabor
      filters: log4j,mergeStat
  mvc:
    view:
      imageLocalPath: http://lximg.jsxywg.cn/labor/
      imageHost: http://lxjs.jsxywg.cn/labor/
      #imageHost: http://localhost:8030/labor/
      imagePathAttendance: /attendance/
      imageLocalPathAttendance: http://192.168.1.124:8888/
  redis:
    host: 192.168.1.143
    port: 6379
    password: Xingyun*_001
    max-idle: 500
    min-idle: 50
    active: 2000
    wait: 1000
    cahce-names: xywg-sbgl-day-2,xywg-sbgl-min-30,xywg-sbgl-min-2,xywg-sbgl-hour-2        

logging:
  level.root: info
  path: logs/
  file: xywg.log

ftp:
  host: 192.168.1.124
  port: 21
  username: lxjs
  password: 123.abc

sync:
  url: http://labor.jsxywg.cn/sync/listDeals

suffix:
  schema: gblabor