##########################################################
###################  开发环境的profile  ###################
##########################################################

xywg:
  ##########################################################
  ###################  任务调度配置        ###################
  ##########################################################
 job:
   admin:
     #addresses: http://192.168.10.158:8083
     addresses: http://192.168.1.17:8083
   executor:
     appname: job-executor-labor
     ip:
     port: 9999
     logpath: logs/xxl-job/jobhandler
     logretentiondays: -1
   accessToken: xywg666

spring:
  datasource:
   # url: jdbc:mysql://192.168.1.129:3306/gblabor?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
   # url: jdbc:mysql://localhost:3306/gblabor?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    url: jdbc:mysql://192.168.10.143:3306/gblabor?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
#    username: root
#    password: 6Yj*kLb0
    username: root
    password: Xingyun*_001
    db-name: gblabor
    filters: log4j,mergeStat
  mvc:
    view:
      #imageLocalPath: http://192.168.1.209/tslabor/
      imageLocalPath: http://192.168.1.209/tslabor/
      imageHost: http://localhost:8030/labor/
  redis:
    host: 192.168.1.17
    #host: localhost
    port: 6379
    password: 123456
    max-idle: 500
    min-idle: 50
    active: 2000
    wait: 1000
    cahce-names: xywg-sbgl-day-2,xywg-sbgl-min-30,xywg-sbgl-min-2,xywg-sbgl-hour-2
  #edis:
  # host: 192.168.10.143
  # #host: 192.168.10.172
  # port: 6379
  # password: Xingyun*_001
  # max-idle: 500
  # min-idle: 50
  # active: 2000
  # wait: 1000
  # cahce-names: xywg-sbgl-day-2,xywg-sbgl-min-30,xywg-sbgl-min-2,xywg-sbgl-hour-2
      
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: xywg.log

ftp:
  host: 192.168.1.209
  port: 21
  username: labor
  password: 123456

sync:
  url: http://192.168.20.176:8010/sync/listDeals

suffix:
  schema: gblabor